export const STATUS_LOADING = 'loading'
export const STATUS_LOADED = 'loaded'
export const STATUS_FETCHING = 'fetching'
export const STATUS_FETCHED = 'fetched'
export const STATUS_FETCH_FAILED = 'fetched_failed'
export const STATUS_SENDING = 'sending'
export const STATUS_ERROR = 'error'
export const STATUS_DEFAULT = 'default'
export const STATUS_NOT_FOUND = 'not_found'
export const STATUS_SUCCESS = 'success'

export const STATUS_UPDATED = 'updated'
export const STATUS_EDITING = 'editing'
export const STATUS_CREATED = 'created'
export const STATUS_DELETED = 'deleted'
