export const STATUS_LOADING = 'loading'
export const STATUS_LOADED = 'loaded'
export const STATUS_FETCHING = 'fetching'
export const STATUS_FETCHED = 'fetched'
export const STATUS_FETCH_FAILED = 'fetched_failed'
export const STATUS_SENDING = 'sending'
export const STATUS_ERROR = 'error'
export const STATUS_DEFAULT = 'default'
export const STATUS_NOT_FOUND = 'not_found'
export const STATUS_SUCCESS = 'success'

export const STATUS_UPDATED = 'updated'
export const STATUS_EDITING = 'editing'
export const STATUS_CREATED = 'created'

export const PRODUCT_FIELD_ID = 'id'
export const PRODUCT_FIELD_TITLE = 'title'
export const PRODUCT_FIELD_DESCRIPTION = 'description'
export const PRODUCT_FIELD_LINK = 'link'
export const PRODUCT_FIELD_IMAGE = 'image'
export const PRODUCT_FIELD_BARCODE = 'barcode'
export const PRODUCT_FIELD_CATEGORY_IDS = 'category_ids'
export const PRODUCT_FIELD_CATEGORIES = 'categories'
export const PRODUCT_FIELD_LIST_ID = 'list_id'
export const PRODUCT_FIELD_LIST = 'list'

export const STOCK_ADD_FORM_QUANTITY = 'quantity'
export const STOCK_ADD_FORM_EXPIRE = 'expire'
