name: Release docker image with latest proviant version

on:
  release:
    types:
      - released
    tags:
      - '*'

env:
  TAG: ${{ github.event.release.tag_name }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  build-ce:
    name: Build and publish assets for CE
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - run: make docker/release/ce

  build-saas:
    name: Build and publish assets fpr SaaS
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - run: make docker/release/saas
